from dbConnection.connection import get_connection

def create_table():
    conn = get_connection()
    cursor = conn.cursor()

    # Check if table exists in HANA
    cursor.execute("""
        SELECT COUNT(*) 
        FROM TABLES 
        WHERE SCHEMA_NAME = CURRENT_SCHEMA AND TABLE_NAME = 'CV_Info'
    """)

    cv_exists = cursor.fetchone()[0]

    cursor.execute("""
        SELECT COUNT(*)
        FROM TABLES
        WHERE SCHEMA_NAME = CURRENT_SCHEMA AND TABLE_NAME = 'JOB_Info'
    """)

    job_exists = cursor.fetchone()[0]

    if cv_exists == 0:
        cursor.execute("""
            CREATE TABLE CV_Info (
                ID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                NAME NVARCHAR(50),
                EMAIL NVARCHAR(100),
                ATTACHMENT BLOB,
                STATUS NVARCHAR(50)
            )
        """)

    if job_exists == 0:
        cursor.execute("""
            CREATE TABLE JOB_Info (
                ID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                JOB_TITLE NVARCHAR(100),
                JOB_DESCRIPTION NCLOB
            )
        """)
        print("Table created successfully!")

    if cv_exists != 0 and job_exists != 0:
        print("Tables already exist")

    conn.commit()
    cursor.close()
    conn.close()

def insert_job(job_title, job_description):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("INSERT INTO JOB_Info (JOB_TITLE, JOB_DESCRIPTION) VALUES ( ?, ?)", (job_title, job_description))
    conn.commit()
    cursor.close()
    conn.close()
    print("Job description stored successfully")

